[package]
name = "rusty_dependencies"
version = "0.1.0"
edition = "2018"

[lib]
name = "rusty_dependencies"
path = "src/lib.rs"

[dependencies]
reqwest = {version = ">=0.11.7", features = ["blocking"]}
error-chain = ">=0.12.4"